packages:
  - "packages/*"

allowBuilds:
  better-sqlite3: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

minimumReleaseAgeExclude:
  - '@simplebrains/recital@0.8.0'
  - '@omgbase/oqx@0.2.0 || 0.3.0 || 0.4.0 || 0.5.0 || 0.6.0 || 0.7.0 || 0.8.0 || 0.9.0'
