// The VS Code language extension under `vscode/`: its manifest and the Markdown
// injection grammar that highlights ```oqx fenced blocks. Both are generated by
// `scripts/generate.mjs` (the extension is packaged with `vsce package` from
// that directory; it has no code, only contributions).

import { LANGUAGE } from "./vocabulary.js";

export const MARKDOWN_INJECTION_SCOPE = "markdown.oqx.codeblock";
export const MARKDOWN_EMBEDDED_SCOPE = "meta.embedded.block.oqx";

/** An injection grammar into `text.html.markdown`: a fenced block whose info
 * string names the language is highlighted with `source.oqx`. */
export function buildMarkdownInjectionGrammar(): Record<string, unknown> {
  const langs = LANGUAGE.fenceLanguages.join("|");
  return {
    $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    scopeName: MARKDOWN_INJECTION_SCOPE,
    injectionSelector: "L:text.html.markdown",
    fileTypes: [],
    patterns: [{ include: "#oqx-code-block" }],
    repository: {
      "oqx-code-block": {
        begin: `(^|\\G)(\\s*)(\`{3,}|~{3,})\\s*(?i:(${langs})((\\s+|:|,|\\{|\\?)[^\`]*)?$)`,
        name: "markup.fenced_code.block.markdown",
        end: "(^|\\G)(\\2|\\s{0,3})(\\3)\\s*$",
        beginCaptures: {
          "3": { name: "punctuation.definition.markdown" },
          "4": { name: "fenced_code.block.language.markdown" },
          "5": { name: "fenced_code.block.language.attributes.markdown" },
        },
        endCaptures: { "3": { name: "punctuation.definition.markdown" } },
        patterns: [
          {
            begin: "(^|\\G)(\\s*)(.*)",
            while: "(^|\\G)(?!\\s*([`~]{3,})\\s*$)",
            contentName: MARKDOWN_EMBEDDED_SCOPE,
            patterns: [{ include: LANGUAGE.scopeName }],
          },
        ],
      },
    },
  };
}

/** The extension manifest (`vscode/package.json`). */
export function buildVsCodeManifest(version: string): Record<string, unknown> {
  return {
    name: "oqx-syntax",
    displayName: "OQX Syntax",
    description: "Syntax highlighting for OQX (omgbase Query eXpressions) files and ```oqx Markdown fences",
    version,
    publisher: "omgbase",
    license: "MIT",
    repository: { type: "git", url: "https://github.com/omgbase/omgbase.git", directory: "packages/oqx-syntax/vscode" },
    engines: { vscode: "^1.80.0" },
    categories: ["Programming Languages"],
    keywords: ["oqx", "omgbase", "query", "syntax", "highlighting"],
    contributes: {
      languages: [
        {
          id: LANGUAGE.id,
          aliases: [...LANGUAGE.aliases],
          extensions: [...LANGUAGE.extensions],
          mimetypes: [...LANGUAGE.mimeTypes],
          configuration: "./language-configuration.json",
        },
      ],
      grammars: [
        { language: LANGUAGE.id, scopeName: LANGUAGE.scopeName, path: "./syntaxes/oqx.tmLanguage.json" },
        {
          scopeName: MARKDOWN_INJECTION_SCOPE,
          path: "./syntaxes/oqx.markdown-injection.tmLanguage.json",
          injectTo: ["text.html.markdown"],
          embeddedLanguages: { [MARKDOWN_EMBEDDED_SCOPE]: LANGUAGE.id },
        },
      ],
    },
  };
}
